---
title: "Clickable PreScreening List"
description: print list for prescreeners to click sampled items conveniently
author: "Timo Roettger"
date: "Last update: `r Sys.Date()`"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## R Markdown

```{r display_list, echo = FALSE, message = FALSE, warning = FALSE}

list <- read_tsv(file = "../data/prescreening_list_2021-07-04.txt")
list_sub <- list %>% 
  mutate(row_num = seq.int(nrow(list))) %>% 
  select(row_num, ID, clickable_doi, Title, Year, Authors) 

knitr::kable(list_sub)

```

Print out the list for working with others:

```{r}
list_sub$year_split <- list_sub$Year < 2015
list_sub$year_split <- factor(list_sub$year_split, 
                           levels = c(TRUE, FALSE),
                           labels = c("Pre-OS", "After-OS"))

write.csv(list_sub, "prescreening.csv", row.names = F)
```

## Analysis

```{r}
pilot <- read.csv("pilot_prescreening.csv")

# reduce just to articles piloted 
pilot <- subset(pilot, !is.na(count))

# number piloted
nrow(pilot)

# create year variable
pilot$year_split <- pilot$Year < 2015
pilot$year_split <- factor(pilot$year_split, 
                           levels = c(TRUE, FALSE),
                           labels = c("Pre-OS", "After-OS"))
table(pilot$year_split)

# examine yes/no/na 
# note that NA means we couldn't find a copy of the article 
table(pilot$year_split, pilot$erin.code, useNA = "ifany")

table(pilot$year_split, pilot$erin.code, useNA = "ifany")/25 * 100

# examine overall
table(pilot$erin.code, useNA = "ifany")

table(pilot$erin.code, useNA = "ifany")/50 * 100
```


